### ISSUE TITLE
pub get & pub upgrade fail after upgrading the editor to 1.6.0.dev_09_03

### ISSUE THREAD

**Issue by DartBot** [dart-lang/polymer-dart#430]
<a href="https://github.com/jolleekin"><img src="https://avatars.githubusercontent.com/u/5405376?v=3" align="left" width="96" height="96"hspace="10"></img></a> **Issue by [jolleekin](https://github.com/jolleekin)**
_Originally opened as dart-lang/sdk#20621_

----

After upgrading the editor to 1.6.0.dev_09_03, I keep seeing the following error when trying to run pub get or pub upgrade.

&nbsp;&nbsp;&nbsp;&nbsp;Pub get failed, [3] vm\object.cc:17891: error: Fatal error in Array::New: invalid len -6

&nbsp;&nbsp;&nbsp;&nbsp;Pub upgrade failed, [3] vm\object.cc:17891: error: Fatal error in Array::New: invalid len -6

**What version of the product are you using?**
Dart Editor 1.6.0.dev_09_03

**On what operating system?**
Windows 8.1 64bit

**What browser (if applicable)?**

**Please provide any additional information below.**

**Comment by DartBot** [comment]
<a href="https://github.com/jolleekin"><img src="https://avatars.githubusercontent.com/u/5405376?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [jolleekin](https://github.com/jolleekin)**

----

The error happened after upgrading the editor through the About dialog. I tried deleting the dart folder and downloading the editor again through https://dartlang.org/tools/download.html, and the error was gone. However, there is another error with build.


--- 11:50:30 AM build.dart --machine --changed=web\pages\abc_xyz.dart ---
file:/C:/Users/mhoang/Documents/GitHub/abc/build.dart
build.dart returned error code 255

Unhandled exception:
Uncaught Error: Converting object to an encodable object failed.
Stack Trace:
#&#173;0      \_JsonStringifier.stringifyValue (dart:convert/json.dart:489)
#&#173;1      \_JsonStringifier.stringifyJsonValue.&lt;anonymous closure> (dart:convert/json.dart:543)
#&#173;2      \_HashMap&&_LinkedHashMapMixin.forEach (dart:collection-patch/collection_patch.dart:967)
#&#173;3      \_JsonStringifier.stringifyJsonValue (dart:convert/json.dart:538)
#&#173;4      \_JsonStringifier.stringifyValue (dart:convert/json.dart:480)
#&#173;5      \_JsonStringifier.stringifyJsonValue.&lt;anonymous closure> (dart:convert/json.dart:543)
#&#173;6      \_HashMap&&_LinkedHashMapMixin.forEach (dart:collection-patch/collection_patch.dart:967)
#&#173;7      \_JsonStringifier.stringifyJsonValue (dart:convert/json.dart:538)
#&#173;8      \_JsonStringifier.stringifyValue (dart:convert/json.dart:480)
#&#173;9      \_JsonStringifier.stringifyJsonValue (dart:convert/json.dart:524)
#&#173;10     \_JsonStringifier.stringifyValue (dart:convert/json.dart:480)
#&#173;11     \_JsonStringifier.printOn (dart:convert/json.dart:409)
#&#173;12     \_JsonStringifier.stringify (dart:convert/json.dart:403)
#&#173;13     JsonEncoder.convert (dart:convert/json.dart:239)
#&#173;14     JsonCodec.encode (dart:convert/json.dart:141)
#&#173;15     \_jsonFormatter (package:polymer/src/build/runner.dart:345:21)
#&#173;16     \_attachListeners.&lt;anonymous closure> (package:polymer/src/build/runner.dart:216:27)
#&#173;17     \_rootRunUnary (dart:async/zone.dart:840)
#&#173;18     \_RootZone.runUnaryGuarded (dart:async/zone.dart:1022)
#&#173;19     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;20     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;21     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;22     \_BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:237)
#&#173;23     \_onLog (package:barback/src/graph/package_graph.dart:204:25)
#&#173;24     \_rootRunUnary (dart:async/zone.dart:840)
#&#173;25     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;26     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;27     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;28     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;29     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;30     add (dart:async/broadcast_stream_controller.dart:237)
#&#173;31     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;32     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;33     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;34     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;35     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;36     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;37     add (dart:async/broadcast_stream_controller.dart:237)
#&#173;38     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;39     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;40     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;41     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;42     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;43     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;44     add (dart:async/broadcast_stream_controller.dart:237)
#&#173;45     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;46     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;47     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;48     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;49     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;50     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;51     add (dart:async/broadcast_stream_controller.dart:237)
#&#173;52     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;53     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;54     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;55     \_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#&#173;56     \_BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#&#173;57     \_SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:346)
#&#173;58     \_BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:237)
#&#173;59     BaseTransform.BaseTransform.&lt;anonymous closure> (package:barback/src/transformer/base_transform.dart:52:27)
#&#173;60     TransformLogger.warning (package:barback/src/transformer/transform_logger.dart:50:17)
#&#173;61     \_LinterVisitor._validateNormalElement (package:polymer/src/build/linter.dart:365:22)
#&#173;62     \_LinterVisitor.visitElement (package:polymer/src/build/linter.dart:191:32)
#&#173;63     TreeVisitor.visit (package:html5lib/dom_parsing.dart:12:50)
#&#173;64     TreeVisitor.visitChildren (package:html5lib/dom_parsing.dart:24:49)
#&#173;65     TreeVisitor.visitNodeFallback (package:html5lib/dom_parsing.dart:30:48)
#&#173;66     TreeVisitor.visitElement (package:html5lib/dom_parsing.dart:39:50)
#&#173;67     \_LinterVisitor.visitElement (package:polymer/src/build/linter.dart:192:28)
#&#173;68     TreeVisitor.visit (package:html5lib/dom_parsing.dart:12:50)
#&#173;69     TreeVisitor.visitChildren (package:html5lib/dom_parsing.dart:24:49)
#&#173;70     TreeVisitor.visitNodeFallback (package:html5lib/dom_parsing.dart:30:48)
#&#173;71     TreeVisitor.visitElement (package:html5lib/dom_parsing.dart:39:50)
#&#173;72     \_LinterVisitor._validatePolymerElement (package:polymer/src/build/linter.dart:286:23)
#&#173;73     \_LinterVisitor.visitElement (package:polymer/src/build/linter.dart:188:54)
#&#173;74     TreeVisitor.visit (package:html5lib/dom_parsing.dart:12:50)
#&#173;75     TreeVisitor.visitChildren (package:html5lib/dom_parsing.dart:24:49)
#&#173;76     TreeVisitor.visitNodeFallback (package:html5lib/dom_parsing.dart:30:48)
#&#173;77     TreeVisitor.visitElement (package:html5lib/dom_parsing.dart:39:50)
#&#173;78     \_LinterVisitor.visitElement (package:polymer/src/build/linter.dart:192:28)
#&#173;79     TreeVisitor.visit (package:html5lib/dom_parsing.dart:12:50)
#&#173;80     TreeVisitor.visitChildren (package:html5lib/dom_parsing.dart:24:49)
#&#173;81     TreeVisitor.visitNodeFallback (package:html5lib/dom_parsing.dart:30:48)
#&#173;82     TreeVisitor.visitElement (package:html5lib/dom_parsing.dart:39:50)
#&#173;83     \_LinterVisitor.visitElement (package:polymer/src/build/linter.dart:192:28)
#&#173;84     TreeVisitor.visit (package:html5lib/dom_parsing.dart:12:50)
#&#173;85     TreeVisitor.visitChildren (package:html5lib/dom_parsing.dart:24:49)
#&#173;86     TreeVisitor.visitNodeFallback (package:html5lib/dom_parsing.dart:30:48)
#&#173;87     TreeVisitor.visitDocument (package:html5lib/dom_parsing.dart:32:52)
#&#173;88     TreeVisitor.visit (package:html5lib/dom_parsing.dart:16:52)
#&#173;89     \_LinterVisitor.run (package:polymer/src/build/linter.dart:198:10)
#&#173;90     Linter.apply.&lt;anonymous closure>.&lt;anonymous closure> (package:polymer/src/build/linter.dart:47:67)
#&#173;91     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;92     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;93     \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#&#173;94     \_Future._propagateToListeners (dart:async/future_impl.dart:571)
#&#173;95     \_Future._complete (dart:async/future_impl.dart:317)
#&#173;96     Future.doWhile.&lt;anonymous closure> (dart:async/future.dart:330)
#&#173;97     \_rootRunUnary (dart:async/zone.dart:836)
#&#173;98     \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;99     \_CustomZone.runUnaryGuarded (dart:async/zone.dart:656)
#&#173;100    \_CustomZone.bindUnaryCallback.&lt;anonymous closure> (dart:async/zone.dart:682)
#&#173;101    \_rootRunUnary (dart:async/zone.dart:836)
#&#173;102    \_CustomZone.runUnary (dart:async/zone.dart:748)
#&#173;103    \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#&#173;104    \_Future._propagateToListeners (dart:async/future_impl.dart:571)
#&#173;105    \_Future._completeWithValue (dart:async/future_impl.dart:331)
#&#173;106    \_Future._asyncComplete.&lt;anonymous closure> (dart:async/future_impl.dart:393)
#&#173;107    \_rootRun (dart:async/zone.dart:829)
#&#173;108    \_CustomZone.run (dart:async/zone.dart:740)
#&#173;109    \_CustomZone.runGuarded (dart:async/zone.dart:648)
#&#173;110    \_CustomZone.bindCallback.&lt;anonymous closure> (dart:async/zone.dart:673)
#&#173;111    \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#&#173;112    \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#&#173;113    \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:126)

#&#173;0      \_rootHandleUncaughtError.&lt;anonymous closure> (dart:async/zone.dart:820)
#&#173;1      \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#&#173;2      \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#&#173;3      \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:126)

**Comment by DartBot** [comment]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [sigmundch](https://github.com/sigmundch)**

----

Seems like something broke the default implementation of build.dart for polymer apps with this new SDK.
______
*Set owner to @sigmundch.*
*Added [Area-Pkg](../labels/Area-Pkg), [Pkg-PolymerBuild](../labels/Pkg-PolymerBuild), [Started](../labels/Started) labels.*

**Comment by DartBot** [comment]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [sigmundch](https://github.com/sigmundch)**

----

fix on its way... https://codereview.chromium.org/489423002/

**Comment by DartBot** [comment]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [sigmundch](https://github.com/sigmundch)**

----

the fix will be available on the next polymer release, likely today.
______
*Added [Fixed](../labels/Fixed) label.*
