### ISSUE TITLE
core-selector doesn't work with automatic node finding

### ISSUE THREAD

**Issue by DartBot** [dart-lang/polymer-dart#246]
_Originally opened as dart-lang/sdk#20152_

*This issue was originally filed by Erik.Grimes...&#064;gmail.com*
_____
**What steps will reproduce the problem?**

Create an application with a polymer element defined like so:

&lt;link rel=&quot;import&quot; href=&quot;packages/polymer/polymer.html&quot;&gt;
&lt;link rel='import'
&nbsp;&nbsp;href='packages/core_elements/core_selector.html'&gt;

&lt;polymer-element name=&quot;binding-issue-app&quot;&gt;

&nbsp;&nbsp;&lt;template&gt;
&nbsp;&nbsp;&lt;style&gt;
&nbsp;&nbsp;&nbsp;&nbsp;.active {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;font-weight: bold;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&lt;/style&gt;
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;selected: {{selected}}
&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;core-selector id='navbar-selector' 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;itemsSelector='.coaching-navbar-item' selectedClass='active'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selected='{{selected}}' valueattr='value' target='{{ $[&quot;navbar&quot;] }}'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/core-selector&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&lt;div id='navbar' class='coaching-navbar col-lg-12'&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='one'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;one&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='two'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;two&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='three'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;three&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;     
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/template&gt;
&nbsp;&nbsp;&lt;script type=&quot;application/dart&quot; src=&quot;binding_issue_app.dart&quot;&gt;&lt;/script&gt;
&lt;/polymer-element&gt;

**What is the expected output? What do you see instead?**

Expected: The console should be clear.
Actual: Get the following exception:

&lt;link rel=&quot;import&quot; href=&quot;packages/polymer/polymer.html&quot;&gt;
&lt;link rel='import'
&nbsp;&nbsp;href='packages/core_elements/core_selector.html'&gt;

&lt;polymer-element name=&quot;binding-issue-app&quot;&gt;

&nbsp;&nbsp;&lt;template&gt;
&nbsp;&nbsp;&lt;style&gt;
&nbsp;&nbsp;&nbsp;&nbsp;.active {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;font-weight: bold;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&lt;/style&gt;
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;selected: {{selected}}
&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;core-selector id='navbar-selector' 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;itemsSelector='.coaching-navbar-item' selectedClass='active'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selected='{{selected}}' valueattr='value' target='{{ $[&quot;navbar&quot;] }}'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/core-selector&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&lt;div id='navbar' class='coaching-navbar col-lg-12'&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='one'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;one&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='two'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;two&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div value='three'&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;three&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;     
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/template&gt;
&nbsp;&nbsp;&lt;script type=&quot;application/dart&quot; src=&quot;binding_issue_app.dart&quot;&gt;&lt;/script&gt;
&lt;/polymer-element&gt;

**What version of the product are you using?**

Dart SDK: 1.5.3
Polymer: 0.11.0+5
core_elements: 0.6.0

**On what operating system?**

**What browser (if applicable)?**
Chromium: 36.0.1985.97 (280598)

**Please provide any additional information below.**

This pattern for using core_selector is straight out of the core_selector demo.

**Comment by DartBot** [comment]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [sigmundch](https://github.com/sigmundch)**

----

> Actual: Get the following exception:

would you mind pasting the exception once again - it looks like the code was pasted twice instead.


Just from quick look though, I think this might also be related to the issue you mentioned in 20154 -- the binding to target might not be working.

When we fixed issue dart-lang/polymer-dart#224, we basically fixed that bindings with polymer-js elements were not working that well, especially two-way bindings. We had demos where we had to query for the element in code and set the value of the property (in this case `target`) programmatically. We got rid of those workarounds after we started using 0.12.0-dev in the elements packages.

Let us know if you are still seeing the issue if you try the 0.12.0-dev prerelease, though.

Thanks!
______
*Added [Pkg-Polymer](../labels/Pkg-Polymer), [Area-Pkg](../labels/Area-Pkg), [PolymerMilestone-Next](../labels/PolymerMilestone-Next), [NeedsInfo](../labels/NeedsInfo) labels.*

**Comment by DartBot** [comment]
*This comment was originally written by Erik.Grimes...&#064;gmail.com*
_____
Woops!  Here's  the exception...

Exception caught during observer callback: TypeError: undefined is not a function
&nbsp;&nbsp;&nbsp;&nbsp;at core-selector.Polymer.addListener (http://127.0.0.1:8080/core_selector_binding.html:590:14)
&nbsp;&nbsp;&nbsp;&nbsp;at core-selector.Polymer.targetChanged (http://127.0.0.1:8080/core_selector_binding.html:583:16)
&nbsp;&nbsp;&nbsp;&nbsp;at core-selector.g.invokeMethod (http://127.0.0.1:8080/packages/polymer/src/js/polymer/polymer.js:12:13320)
&nbsp;&nbsp;&nbsp;&nbsp;at core-selector.g.notifyPropertyChanges (http://127.0.0.1:8080/packages/polymer/src/js/polymer/polymer.js:12:11606)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.Observer.report_ (http://127.0.0.1:8080/packages/web_components/platform.js:12:12616)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.createObject.check_ (http://127.0.0.1:8080/packages/web_components/platform.js:12:18105)
&nbsp;&nbsp;&nbsp;&nbsp;at c (http://127.0.0.1:8080/packages/web_components/platform.js:12:5467) (http://127.0.0.1:8080/packages/web_components/platform.js:12)

I can confirm this issue is fixed in 0.12.0-dev.

**Comment by DartBot** [comment]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="48" height="48"hspace="10"></img></a> **Comment by [sigmundch](https://github.com/sigmundch)**

----

Great to hear it works in 0.12.0-dev. Thanks for the update!

______
*Added [AssumedStale](../labels/AssumedStale) label.*
